services:
  postgres:
    image: postgres:latest
    container_name: postgres-startup
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: startup
    ports:
      - "5429:5432"           
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:            
  postgres_data: 