import type { Metadata } from "next";
import "./global.css";
import { I18nProvider } from "./providers/i18n-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" className="w-full h-full ">
      <body className="w-full h-full flex items-center justify-center bg-[#202020]">
        <div className="w-full h-full max-w-120 max-h-240 relative bg-(--page-bg)">
          <I18nProvider>{children}</I18nProvider>
        </div>
      </body>
    </html>
  );
}
